pipeline {
    agent any

    environment {
        DOCKER_IMAGE_NAME = "demo-app"
        DOCKERFILE_PATH = "./docker/Dockerfile"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    sh 'pwd'
                    sh 'ls'
                                        // Use the 'docker' command to check if Docker is installed
                    def dockerInstalled = sh(script: 'command -v docker', returnStatus: true) == 0

                    if (dockerInstalled) {
                        echo 'Docker is installed on this agent.'
                    } else {
                        error 'Docker is not installed on this agent. Please install Docker before running this job.'
                    }
                    // dockerImage = docker.build(env.DOCKER_IMAGE_NAME, "-f ${env.DOCKERFILE_PATH} .")
                }
            }
        }

        // stage('Lint and Scan') {
        //     steps {
                
        //         sh './mvnw checkstyle:check'
        //     }
        // }

        // stage('Deploy to Dev') {
        //     when {
        //         branch 'dev'
        //     }
        //     steps {
        //         script {
        //             sh 'deploy-to-dev.sh'
        //         }
        //     }
        // }

        // stage('Deploy to Stage') {
        //     when {
        //         branch 'stage'
        //     }
        //     steps {
        //         script {
        //             sh 'deploy-to-stage.sh'
        //         }
        //     }
        // }

        // stage('Deploy to Prod') {
        //     when {
        //         branch 'prod'
        //     }
        //     steps {
        //         script {
        //             sh 'deploy-to-prod.sh'
        //         }
        //     }
        // }
    }
}
